/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as GGroupIdIndexRouteImport } from './routes/g.$groupId.index'
import { Route as GGroupIdAddRouteImport } from './routes/g.$groupId.add'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GGroupIdIndexRoute = GGroupIdIndexRouteImport.update({
  id: '/g/$groupId/',
  path: '/g/$groupId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GGroupIdAddRoute = GGroupIdAddRouteImport.update({
  id: '/g/$groupId/add',
  path: '/g/$groupId/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/join/$token': typeof JoinTokenRoute
  '/g/$groupId/add': typeof GGroupIdAddRoute
  '/g/$groupId/': typeof GGroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/join/$token': typeof JoinTokenRoute
  '/g/$groupId/add': typeof GGroupIdAddRoute
  '/g/$groupId': typeof GGroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/join/$token': typeof JoinTokenRoute
  '/g/$groupId/add': typeof GGroupIdAddRoute
  '/g/$groupId/': typeof GGroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/sign-in' | '/join/$token' | '/g/$groupId/add' | '/g/$groupId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/join/$token' | '/g/$groupId/add' | '/g/$groupId'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/join/$token'
    | '/g/$groupId/add'
    | '/g/$groupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  JoinTokenRoute: typeof JoinTokenRoute
  GGroupIdAddRoute: typeof GGroupIdAddRoute
  GGroupIdIndexRoute: typeof GGroupIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$groupId/': {
      id: '/g/$groupId/'
      path: '/g/$groupId'
      fullPath: '/g/$groupId/'
      preLoaderRoute: typeof GGroupIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$groupId/add': {
      id: '/g/$groupId/add'
      path: '/g/$groupId/add'
      fullPath: '/g/$groupId/add'
      preLoaderRoute: typeof GGroupIdAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  JoinTokenRoute: JoinTokenRoute,
  GGroupIdAddRoute: GGroupIdAddRoute,
  GGroupIdIndexRoute: GGroupIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
